spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 88114188
    url: jdbc:mysql://127.0.0.1:3306/codeproject?characterEncoding=utf-8&useSSL=false
    #统计拦截的filters wall用于防火墙
    filters: stat,wall,log4j,
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待时间
    maxWait: 60000
    #打开PSCache
    poolPreparedStatements: true
    #指定每个连接的PSCache大小
    maxPoolPreparedPerStatements: 20
    #打开mergeSql：慢Sql记录
    connectProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minldle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictabledleTimeMillis: 300000
    validationQuery: select1 frome dual
    testWhileldle: true
    testOnBorrow: false
    testOnReturn: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null #全局
server:
  servlet:
    context-path: /shop